### ISSUE TITLE
activation_quant max dim seems to be wrong

### ISSUE THREAD

**Issue by justyx404** [joey00072/ohara#11]
According to what's on the FAQ, the dim [here](https://github.com/joey00072/ohara/blob/a598db9fd5e854ac756d7f508a032d8e31ebe372/experiments/bitnet/bitnet.py#L31C1-L32C1) should be -1 instead which will be the embedding dim instead of the seq_len dim.

I also took a look at https://huggingface.co/NousResearch/OLMo-Bitnet-1B/blob/main/model.py#L398

The BitNet158 paper also mentioned that the activation quant is applied per token, 
> activations are all scaled to [−Qb, Qb] per token to get rid of the zero-point quantization

**Comment by joey00072** [comment]
aah, you are right. I'll fix it
Thanks @g1y5x3

**Comment by joey00072** [comment]
fixed
