### ISSUE TITLE
Error when trying to load dataset

### ISSUE THREAD

**Issue by kmcho2019** [joey00072/ohara#7]
When running example/prepare-dataset.py before training model the following error occurs.

![image](https://github.com/joey00072/ohara/assets/91612340/5fb07199-980e-445c-ad9c-cb8438830f86)

I have tried "rm -rf /home/kmcho/.cache/huggingface/datasets/roneneldan___tiny_stories/default/0.0.0/691b0d9bd48ade766778c940011ca1c549f6359b" before running it again but the same error occurs.

I am running this on CentOS 7 linux.

**Comment by joey00072** [comment]
can you try to remove hole `rm -rf ~/.cache/huggingface`,
its tokenizing it correctly but have issues saving it. I don't have centos system right now.
looks like we have to raise this to upstream [datasets](https://github.com/huggingface/datasets).

this works fine on ubuntu btw https://colab.research.google.com/drive/1Mu_mwAWldoXjOtKVLuVNB-Lz9FTe-0og?usp=sharing

isn't centos 7 at EOL

**Comment by kmcho2019** [comment]
It technically has 3 months left I believe.
![image](https://github.com/joey00072/ohara/assets/91612340/f7a40c09-be80-4e8a-bc4d-d17b9301ada3)

I should really upgrade to something like Rocky 8 but, it is going to be such a pain to do it.

Anyway thanks for the answer. I guess I will try it with a Ubuntu docker image if the problem is CentOS 7.

**Comment by kmcho2019** [comment]
The problem seems to be definitely with CentOS 7. When I tried it in my Ubuntu docker image it worked fine.
![image](https://github.com/joey00072/ohara/assets/91612340/ca02193a-5762-42cb-8f15-59d3d58b1882)
